// Auth
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECT_SINGLE_PRODUCT = 'SELECT_SINGLE_PRODUCT';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';

// Warehouse
export const GET_WAREHOUSES = 'GET_WAREHOUSES';
export const SELECT_SINGLE_WAREHOUSE = 'SELECT_SINGLE_WAREHOUSE';
export const ADD_WAREHOUSES = 'ADD_WAREHOUSES';
export const EDIT_WAREHOUSES = 'EDIT_WAREHOUSES';
export const DELETE_WAREHOUSES = 'DELETE_WAREHOUSES';