// Auth
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECT_SINGLE_PRODUCT = 'SELECT_SINGLE_PRODUCT';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';

// Warehouse
export const GET_WAREHOUSES = 'GET_WAREHOUSES';
export const SELECT_SINGLE_WAREHOUSE = 'SELECT_SINGLE_WAREHOUSE';
export const ADD_WAREHOUSES = 'ADD_WAREHOUSES';
export const EDIT_WAREHOUSES = 'EDIT_WAREHOUSES';
export const DELETE_WAREHOUSES = 'DELETE_WAREHOUSES';
export const DISPLAY_WAREHOUSE = 'DISPLAY_WAREHOUSE';

// Warehouse Stock
export const ADD_WAREHOUSE_STOCK = 'ADD_WAREHOUSE_STOCK';


// User
export const GET_USERS = 'GET_USERS';
export const SELECT_SINGLE_USER = 'SELECT_SINGLE_USER';
export const ADD_USER = 'ADD_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const DISPLAY_USER = 'DISPLAY_USER';

// Role
export const GET_ROLES = 'GET_ROLES';
export const SELECT_SINGLE_ROLE = 'SELECT_SINGLE_ROLE';
export const ADD_ROLE = 'ADD_ROLE';
export const EDIT_ROLE = 'EDIT_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const DISPLAY_ROLE = 'DISPLAY_ROLE';