// Auth
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECT_SINGLE_PRODUCT = 'SELECT_SINGLE_PRODUCT';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';